spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: subash
    password: subash
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8020

app:
  security:
    jwt:
      access-token-exp: 86400000 #24 hrs
      refresh-token-exp: 604800000 #7 days