spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: subash
    password: subash
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: customerGroup
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: com.abs.e_commerce.dto.CustomerRegistration
        spring.json.use.type.headers: false

  grpc:
    server:
      port: 9090

server:
  port: 8090

eureka:
  instance:
    metadata-map:
      gRPC: ${spring.grpc.server.port}
