spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: subash
    password: subash
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  grpc:
    server:
      port: 9090

server:
  port: 8090

eureka:
  instance:
    metadata-map:
      gRPC: ${spring.grpc.server.port}
