spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: subash
    password: subash
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false

  grpc:
    server:
      port: 9060

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.abs.e_commerce.dto.PaymentNotificationRequest

server:
  port: 8060

eureka:
  instance:
    metadata-map:
      gRPC: ${spring.grpc.server.port}