spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: subash
    password: subash
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false

  grpc:
    server:
      port: 9050

server:
  port: 8050

eureka:
  instance:
    metadata-map:
      gRPC: ${spring.grpc.server.port}
